/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import domain.Cliente;
import domain.Factura;
import domain.MetodosCliente;
import domain.MetodosDocumentos;
import domain.MetodosProducto;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    int ncuotas = 0;
    int cfactura = 0;
    int ccontrato = 0;
    int codigoCliente = 0;
    Factura nuevaFactura = new Factura();

    public Venta() {
        initComponents();
        cargarClientes();
        cargarProductos();
        ccuotas.setEnabled(false);
        bproducto.setEnabled(false);
        inproducto.setEditable(false);
        setLocationRelativeTo(null);
                        bmenu.setOpaque(false);
        bmenu.setContentAreaFilled(false);
        bmenu.setBorderPainted(false);
        bmenu.setCursor(new Cursor(HAND_CURSOR));
    }

    public void ingreso() {
        JOptionPane.showMessageDialog(null, "SE CREO FACTURA CON EXITO\n" + "CODIGO DE FACTURA: " + cfactura);
        JOptionPane.showMessageDialog(null, "SE CREO CONTRATO CON EXITO\n" + "CODIGO DE CONTRATO: " + ccontrato);
        incliente.setText("");
        inproducto.setText("");
        mcliente.setText("");
        init.setText("");
        init.setText("");
        mproducto.setText("");
        mprecio.setText("");
        mcuota.setText("");
        incliente.requestFocus();
        idir.setText("");
        grupocuotas.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupocuotas = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelVenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        incliente = new javax.swing.JTextField();
        precio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inproducto = new javax.swing.JTextField();
        mproducto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bmenu = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mprecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mcuota = new javax.swing.JLabel();
        bproducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        init = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mcliente = new javax.swing.JLabel();
        ccuotas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        docec = new javax.swing.JRadioButton();
        tresc = new javax.swing.JRadioButton();
        diezc = new javax.swing.JRadioButton();
        seisc = new javax.swing.JRadioButton();
        idir = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jPanelMostrarClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jLabelClienteSeleccionado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        productoSeleccionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo Cliente");

        incliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclienteActionPerformed(evt);
            }
        });
        incliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inclienteKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CODIGO PRODUCTO");

        inproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inproductoActionPerformed(evt);
            }
        });
        inproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inproductoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CANTIDAD DE CUOTAS");

        bmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmenuActionPerformed(evt);
            }
        });

        ingresar.setText("Grabar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PRECIO DEL PRODUCTO");

        mprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("MONTO DE CADA CUOTA");

        mcuota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bproducto.setText("Buscar Producto");
        bproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bproductoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DIRECCION");

        init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("NIT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("NOMBRE Y APELLIDO");

        ccuotas.setText("Calcular Pago de Cuotas");
        ccuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccuotasActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        grupocuotas.add(docec);
        docec.setText("12 Cuotas");
        jPanel2.add(docec);
        docec.setBounds(140, 30, 120, 23);

        grupocuotas.add(tresc);
        tresc.setText("3 Cuotas");
        jPanel2.add(tresc);
        tresc.setBounds(0, 0, 110, 23);

        grupocuotas.add(diezc);
        diezc.setText("10 Cuotas");
        jPanel2.add(diezc);
        diezc.setBounds(0, 30, 110, 23);

        grupocuotas.add(seisc);
        seisc.setText("6 Cuotas");
        jPanel2.add(seisc);
        seisc.setBounds(140, 0, 120, 23);

        idir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idirActionPerformed(evt);
            }
        });

        jButtonBuscarCliente.setText("Buscar Cliente");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentaLayout = new javax.swing.GroupLayout(jPanelVenta);
        jPanelVenta.setLayout(jPanelVentaLayout);
        jPanelVentaLayout.setHorizontalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaLayout.createSequentialGroup()
                .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentaLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVentaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(bproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVentaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(incliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(mcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(idir, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(init, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(inproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)
                            .addComponent(mprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(mproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelVentaLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10))
                                .addGroup(jPanelVentaLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(42, 42, 42)))
                            .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(ccuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelVentaLayout.setVerticalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButtonBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(bproducto)
                .addGap(154, 154, 154)
                .addComponent(bmenu)
                .addGap(53, 53, 53))
            .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVentaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(6, 6, 6)
                    .addComponent(incliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jLabel9)
                    .addGap(6, 6, 6)
                    .addComponent(mcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel5)
                    .addGap(6, 6, 6)
                    .addComponent(idir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)
                    .addComponent(jLabel8)
                    .addGap(6, 6, 6)
                    .addComponent(init, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(mprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addComponent(mproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addGroup(jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVentaLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel6)
                            .addGap(16, 16, 16)
                            .addComponent(mcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addComponent(ccuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Venta", jPanelVenta);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Direccion", "NIT", "Telefono"
            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        jLabelTitle.setText("SELECCIONE UN CLIENTE PARA BUSCAR SUS DOCUMENTOS.");

        jLabelClienteSeleccionado.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelClienteSeleccionado.setForeground(new java.awt.Color(255, 51, 51));
        jLabelClienteSeleccionado.setText("CODIGO SELECCIONADO: ");

        javax.swing.GroupLayout jPanelMostrarClientesLayout = new javax.swing.GroupLayout(jPanelMostrarClientes);
        jPanelMostrarClientes.setLayout(jPanelMostrarClientesLayout);
        jPanelMostrarClientesLayout.setHorizontalGroup(
            jPanelMostrarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarClientesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelMostrarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClienteSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMostrarClientesLayout.setVerticalGroup(
            jPanelMostrarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarClientesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabelTitle)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado clientes", jPanelMostrarClientes);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Stock", "Precio"
            }
        ));
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        productoSeleccionado.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        productoSeleccionado.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(productoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado productos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarClientes() {
        DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        ArrayList<Vector> listadoClientes = MetodosCliente.MostrarClientes();
        int cont = 0;
        modelo.setRowCount(0);
        while (cont < listadoClientes.size()) {
            modelo.addRow(listadoClientes.get(cont));
            cont++;
        }
    }

    private void cargarProductos() {
        DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
        ArrayList<Vector> listadoProductos = MetodosProducto.ConsultarTodo();
        int cont = 0;
        modelo.setRowCount(0);
        while (cont < listadoProductos.size()) {
            modelo.addRow(listadoProductos.get(cont));
            cont++;
        }
    }
    private void idirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idirActionPerformed

    private void ccuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccuotasActionPerformed
        // TODO add your handling code here:
        try {
            double cuotas = 0;
            double precio = Double.parseDouble(mprecio.getText());

            if (tresc.isSelected()) {
                cuotas = precio / 3;
                //REDONDEAR PRECIO
                DecimalFormat formato = new DecimalFormat("#.00");
                int r = (int) Math.round(cuotas * 100);
                cuotas = r / 100.0;
                ncuotas = 3;
                mcuota.setText(String.valueOf(cuotas));
            }
            if (seisc.isSelected()) {
                cuotas = precio / 6;
                //REDONDEAR PRECIO
                DecimalFormat formato = new DecimalFormat("#.00");
                int r = (int) Math.round(cuotas * 100);
                cuotas = r / 100.0;
                ncuotas = 6;
                mcuota.setText(String.valueOf(cuotas));
            }
            if (diezc.isSelected()) {
                cuotas = precio / 10;
                //REDONDEAR PRECIO
                DecimalFormat formato = new DecimalFormat("#.00");
                int r = (int) Math.round(cuotas * 100);
                cuotas = r / 100.0;
                ncuotas = 10;
                mcuota.setText(String.valueOf(cuotas));
            }
            if (docec.isSelected()) {
                cuotas = precio / 12;
                //REDONDEAR PRECIO
                DecimalFormat formato = new DecimalFormat("#.00");
                int r = (int) Math.round(cuotas * 100);
                cuotas = r / 100.0;
                ncuotas = 12;
                mcuota.setText(String.valueOf(cuotas));
            }
            if (cuotas == 0) {
                JOptionPane.showMessageDialog(null, "SELECCIONE UNA OPCION");
                mcuota.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
            mcuota.setText("");
        }
    }//GEN-LAST:event_ccuotasActionPerformed

    private void initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initActionPerformed

    private void bproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bproductoActionPerformed
        try {
            grupocuotas.clearSelection();
            int id = Integer.parseInt(inproducto.getText());
            boolean existeCodigo;
            existeCodigo = MetodosProducto.ExisteCodigoStock(id);
            int stockProducto = MetodosProducto.CantidadStock(id);
            if (existeCodigo) {
                if (stockProducto > 0) {
                    mproducto.setText(MetodosProducto.MostrarProducto(id));
                    mprecio.setText(MetodosProducto.MostrarPrecioProducto(id));
                    mcuota.setText("");
                    ccuotas.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "NO HAY EXISTENCIA DE ESTE PRODUCTO");
                    mproducto.setText("");
                    mprecio.setText("");
                    mcuota.setText("");
                    ccuotas.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                mproducto.setText("");
                mprecio.setText("");
                mcuota.setText("");
                ccuotas.setEnabled(false);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
            ccuotas.setEnabled(false);
        }
    }//GEN-LAST:event_bproductoActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        Factura nuevaFactura = new Factura();
        try {
            nuevaFactura.setCodigoCliente(Integer.parseInt(incliente.getText()));
            nuevaFactura.setNombre(mcliente.getText());
            nuevaFactura.setDireccion(idir.getText());
            nuevaFactura.setNit(init.getText());
            nuevaFactura.setCodigoProducto(Integer.parseInt(inproducto.getText()));
            nuevaFactura.setNombreProducto(mproducto.getText());
            nuevaFactura.setPrecioProducto(Double.parseDouble(mprecio.getText()));
            nuevaFactura.setCuotas(ncuotas);
            nuevaFactura.setMontoCuota(Double.parseDouble(mcuota.getText()));

            domain.MetodosDocumentos.GrabarNuevaFactura(nuevaFactura);
            cfactura = MetodosDocumentos.CodigoUltimaFactura();
            ccontrato = MetodosDocumentos.CodigoUltimoContrato();
            ingreso();
            cargarProductos();
            bproducto.setEnabled(false);
            ccuotas.setEnabled(false);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void bmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmenuActionPerformed

        incliente.setText("");
        inproducto.setText("");
        mcliente.setText("");
        init.setText("");
        init.setText("");
        mprecio.setText("");
        mproducto.setText("");
        mcuota.setText("");
        ui.VPrincipal mostrar = new ui.VPrincipal();
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bmenuActionPerformed

    private void inproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inproductoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                grupocuotas.clearSelection();
                int id = Integer.parseInt(inproducto.getText());
                boolean existeCodigo;
                existeCodigo = MetodosProducto.ExisteCodigoStock(id);
                int stockProducto = MetodosProducto.CantidadStock(id);
                if (existeCodigo) {
                    if (stockProducto > 0) {
                        mproducto.setText(MetodosProducto.MostrarProducto(id));
                        mprecio.setText(MetodosProducto.MostrarPrecioProducto(id));
                        mcuota.setText("");
                        ccuotas.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "NO HAY EXISTENCIA DE ESTE PRODUCTO");
                        mproducto.setText("");
                        mprecio.setText("");
                        mcuota.setText("");
                        ccuotas.setEnabled(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                    mproducto.setText("");
                    mprecio.setText("");
                    mcuota.setText("");
                    ccuotas.setEnabled(false);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
                ccuotas.setEnabled(false);
            }
        }
    }//GEN-LAST:event_inproductoKeyPressed

    private void inproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inproductoActionPerformed

    private void inclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inclienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int id = Integer.parseInt(incliente.getText());
                boolean existeCliente = MetodosCliente.ExisteCodigoCliente(id);
                if (existeCliente == true) {
                    Cliente detalleCliente = MetodosCliente.DetallesCliente(id);
                    mcliente.setText(detalleCliente.getNombre() + " " + detalleCliente.getApellido());
                    idir.setText(detalleCliente.getDireccion());
                    init.setText(detalleCliente.getNit());
                    bproducto.setEnabled(true);
                    inproducto.requestFocus();
                    inproducto.setEditable(true);
                    if (mproducto.getText().isEmpty()) {
                        ccuotas.setEnabled(false);
                    } else {
                        ccuotas.setEnabled(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                    incliente.requestFocus();
                    bproducto.setEnabled(false);
                    inproducto.setEditable(false);
                    mcliente.setText("");
                    idir.setText("");
                    init.setText("");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
            }
        }
    }//GEN-LAST:event_inclienteKeyPressed

    private void inclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclienteActionPerformed

    }//GEN-LAST:event_inclienteActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        int seleccionar = jTableClientes.rowAtPoint(evt.getPoint());
        String aux = String.valueOf(jTableClientes.getValueAt(seleccionar, 0));
        codigoCliente = Integer.parseInt(aux);
        jLabelClienteSeleccionado.setText("CODIGO SELECCIONADO: " + String.valueOf(jTableClientes.getValueAt(seleccionar, 0)));
        if (codigoCliente != 0) {
            incliente.setText(aux);
            mcliente.setText("");
            idir.setText("");
            init.setText("");
            incliente.requestFocus();
            bproducto.setEnabled(false);
            ccuotas.setEnabled(false);
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        try {
            int id = Integer.parseInt(incliente.getText());
            boolean existeCliente = MetodosCliente.ExisteCodigoCliente(id);
            if (existeCliente == true) {
                Cliente detalleCliente = MetodosCliente.DetallesCliente(id);
                mcliente.setText(detalleCliente.getNombre() + " " + detalleCliente.getApellido());
                idir.setText(detalleCliente.getDireccion());
                init.setText(detalleCliente.getNit());
                inproducto.requestFocus();
                bproducto.setEnabled(true);
                inproducto.setEditable(true);
                if (mproducto.getText().isEmpty()) {
                    ccuotas.setEnabled(false);
                } else {
                    ccuotas.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "CODIGO NO ENCONTRADO, VERIFIQUE");
                incliente.requestFocus();
                bproducto.setEnabled(false);
                inproducto.setEditable(false);
                mcliente.setText("");
                idir.setText("");
                init.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR DATOS, VERIFIQUE");
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        int seleccionar = jTableProductos.rowAtPoint(evt.getPoint());
        int stockProducto;
        String codigoProducto = String.valueOf(jTableProductos.getValueAt(seleccionar, 0));
        String stockProductoString = String.valueOf(jTableProductos.getValueAt(seleccionar, 2));
        stockProducto = Integer.parseInt(stockProductoString);
        if (stockProducto > 0) {
            productoSeleccionado.setText("Producto seleccionado: " + String.valueOf(jTableProductos.getValueAt(seleccionar, 1)));
            inproducto.requestFocus();
            inproducto.setText(codigoProducto);
            grupocuotas.clearSelection();
            ccuotas.setEnabled(false);
            mproducto.setText("");
            mprecio.setText("");
            mcuota.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "NO HAY EXISTENCIA DE ESTE PRODUCTO");
            productoSeleccionado.setText("");
            inproducto.requestFocus();
            inproducto.setText("");
            grupocuotas.clearSelection();
            ccuotas.setEnabled(false);
            mproducto.setText("");
            mprecio.setText("");
            mcuota.setText("");
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmenu;
    private javax.swing.JButton bproducto;
    private javax.swing.JButton ccuotas;
    private javax.swing.JRadioButton diezc;
    private javax.swing.JRadioButton docec;
    private javax.swing.ButtonGroup grupocuotas;
    private javax.swing.JTextField idir;
    private javax.swing.JTextField incliente;
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField init;
    private javax.swing.JTextField inproducto;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClienteSeleccionado;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMostrarClientes;
    private javax.swing.JPanel jPanelVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JLabel mcliente;
    private javax.swing.JLabel mcuota;
    private javax.swing.JLabel mprecio;
    private javax.swing.JLabel mproducto;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel productoSeleccionado;
    private javax.swing.JRadioButton seisc;
    private javax.swing.JRadioButton tresc;
    // End of variables declaration//GEN-END:variables
}
