/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import domain.MetodosDocumentos;
import domain.PlantillaContrato;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author ferna
 */
public class VerContrato extends javax.swing.JFrame {

    /**
     * Creates new form VerContrato
     */
    String texto;
    String mf;
    int idContrato = BuscarFactura.nfactura;
    int idfactura;
    int contrato = 0;
    int ccliente = 0;
    SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
    int cuotas = 0;
    double precio = 0;
    double mcuotas = 0;
    ResultSet res = null;

    public VerContrato() {
        initComponents();
//        vertexto.setLineWrap(true);
        consulta();
        SimpleAttributeSet attribs = new SimpleAttributeSet();
        StyleConstants.setAlignment(attribs, StyleConstants.ALIGN_JUSTIFIED);
        vertexto.setParagraphAttributes(attribs, true);
        vertexto.setText(texto);
        vertexto.setEditable(false);
        setLocationRelativeTo(null);
    }

    public void consulta() {
        Vector detalleContrato = MetodosDocumentos.mostrarDetalleContrato(idContrato);
        contrato = idContrato;
        ccliente = (int) detalleContrato.get(1);
        idfactura = (int) detalleContrato.get(2);
        mf = String.valueOf(detalleContrato.get(3));
        fecha.applyPattern(mf);
        cuotas = (int) detalleContrato.get(4);
        mcuotas = (double) detalleContrato.get(5);

        DecimalFormat formato = new DecimalFormat("#.00");
        precio = cuotas * mcuotas;
        int r = (int) Math.round(precio * 100);
        precio = r / 100.0;

        texto = "Conste por el presente documento, el Contrato de Compra Venta No." + String.valueOf(contrato) + " que celebran de una parte COMERCIAL LIMA S.A. "
                + "empresa constituida bajo las leyes de la Republica de Guatemala, inscrita con la patente de comercio PA87-78 en el Registro"
                + " de Empresas, señalando domicilio 6ta calle 6-28 Zona 6 Guatemala para efectos del presente contrato, debidamente representada por el señor "
                + "JORGE ARMANDO LIMA CONTRERAS, identificado con DPI No. 1234 47852 0124 (a quien en adelante se le denominará “El Vendedor”); y, de la"
                + " otra parte el señor(a) " + BuscarFactura.nombre + " (a quien en adelante se le denominará “El Comprador”).\n"
                + "El comprador se compromete a pagar la cantidad de: Q." + precio + " en un total de " + cuotas + " cuotas de Q." + mcuotas + " cada una y de NO CUMPLIR CON EL PAGO"
                + " ANTES DESCRITO SE PROCEDERA A INICIAR EL PROCESO JURIDICO, para establecer un acuerdo que pueda solventar la deuda o en caso "
                + "lo amerite pueda REALIZARSE UN EMBARGO DE BIENES.\n\n"
                + "AMBAS PARTES LEEN Y FIRMAN EL DOCUMENTO EN COMUN ACUERDO A FECHA " + mf + " ,EN LA CIUDAD DE GUATEMALA";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonToPdf = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vertexto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Firma del comprador");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Firma del vendedor");

        jButtonToPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pdf.png"))); // NOI18N
        jButtonToPdf.setText("Generar PDF");
        jButtonToPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToPdfActionPerformed(evt);
            }
        });

        vertexto.setEditable(false);
        vertexto.setBorder(null);
        vertexto.setFocusable(false);
        jScrollPane2.setViewportView(vertexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(206, 206, 206)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonToPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void jButtonToPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToPdfActionPerformed
        PlantillaContrato nuevoContrato = new PlantillaContrato(texto, contrato);
        if (nuevoContrato.CrearPlantilla()) {
            JOptionPane.showMessageDialog(null, "PDF creado con exito");
        }
    }//GEN-LAST:event_jButtonToPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerContrato.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerContrato.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerContrato.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerContrato.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonToPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane vertexto;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
